### ISSUE TITLE
How to get the result as eyefit

### ISSUE THREAD

**Issue by xjrelc** [zikai1/HGMMEllFit#1]
I try like this but the result emmm

f=imread('eye.png');
g=im2bw(f,graythresh(f));%图像二值化
g = edge(g);
[r, c] = find(g == 1);
rc = [r c];
figure
plot(rc(:,1),rc(:,2),'k.');
axis equal;
title('Input data points');
%parameter setting
N=50;
R=10;
%start ellipse fitting by HGMM
[FittedEllipse]=HGMM_fit(rc,N,R);
figure
plot(rc(:,1),rc(:,2),'k.');
axis equal;
hold on;
title("HGMM-ellipse fitting");
[~,~,tx,ty]=gen_elp([FittedEllipse 0 60 0]);
plot(tx',ty','r-','Linewidth',2);

**Comment by zikai1** [comment]
Hi,
&nbsp; bugua, you need to remove some unrelated edge segments after the edge detection. Could you please let me see your images, i.e., eye.png. Maybe I could find something.&nbsp;


Best and sincere wishes,
Mingyang




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zikai1/HGMMEllFit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月11日(星期二) 下午3:22
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zikai1/HGMMEllFit] How to get the result as eyefit (#1)





 
I try like this but the result emmm
 
f=imread('eye.png');
 g=im2bw(f,graythresh(f));%图像二值化
 g = edge(g);
 [r, c] = find(g == 1);
 rc = [r c];
 figure
 plot(rc(:,1),rc(:,2),'k.');
 axis equal;
 title('Input data points');
 %parameter setting
 N=50;
 R=10;
 %start ellipse fitting by HGMM
 [FittedEllipse]=HGMM_fit(rc,N,R);
 figure
 plot(rc(:,1),rc(:,2),'k.');
 axis equal;
 hold on;
 title("HGMM-ellipse fitting");
 [,,tx,ty]=gen_elp([FittedEllipse 0 60 0]);
 plot(tx',ty','r-','Linewidth',2);

**Comment by xjrelc** [comment]
I wanna use it to fit a simple shape of ship in pic1,and i think this job may be can used in medical like the pic2
![000231_3](https://user-images.githubusercontent.com/32869275/117901481-03caed00-b2fe-11eb-9252-095f461c6a21.jpg)
![insitu7545](https://user-images.githubusercontent.com/32869275/117901745-98cde600-b2fe-11eb-885d-2c2b7752a549.jpg)

**Comment by zikai1** [comment]
Hi,
&nbsp; bugua, I can not see the pic1 very clearly. As for the pic2, you may need to increase the pixel number N and the neighborhood radius R. Of course, removing some unrelated edge segments will improve the fitting speed. I will test your images.


Regards,
Mingyang.




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "zikai1/HGMMEllFit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月12日(星期三) 上午8:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zikai1/HGMMEllFit] How to get the result as eyefit (#1)





 
I wanna use it to fit a simple shape of ship in pic1,and i think this job may be can used in medical like the pic2

**Comment by zikai1** [comment]
If you have no further questions at this time, I will conclude our session. Please feel free to reach out if any additional queries arise in the future.
